"""Define Hyperparameters for augmentation."""

# Noise
MAX_NOISE_STD = 20

# Anomaly Patch
ANOMALY_PATCH_SHAPES = ['rectangle', 'circle']
MAX_ANOMALY_PATCHES = 20
MIN_ANOMALY_PATCHES = 2
MAX_ANOMALY_RECT_DIM = 10
MAX_ANOMALY_CIRCLE_RADIUS = MAX_ANOMALY_RECT_DIM // 2

#Alpha
MAX_RAND_ALPHA_PATCHES = 5
MAX_ALPHA_PATCH_DIM = 100

# Stripes
MAX_AUGMENT_STRIPES = 20
MIN_AUGMENT_STRIPES = 2
MAX_AUGMENT_STRIPE_THICKNESS = 4
MIN_AUGMENT_STRIPE_THICKNESS = 1
